/**
 * Scaffold a variant from src/variants/_template.
 *   pnpm new:variant saas --name "SaaS" --summary "Product UI for the CRM" --based-on brand
 * Runs on Node's built-in TypeScript type stripping (Node ≥ 22.18 / 24).
 */
import { cpSync, existsSync, readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { buildVariant } from '../plugins/dtcg.ts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const variantsDir = path.join(root, 'src/variants');
const template = path.join(variantsDir, '_template');

const { positionals, values } = parseArgs({
  allowPositionals: true,
  options: { name: { type: 'string' }, summary: { type: 'string' }, 'based-on': { type: 'string' } },
});

const id = positionals[0];
if (!id || !/^[a-z][a-z0-9-]*$/.test(id)) {
  console.error('Usage: pnpm new:variant <id> [--name "Name"] [--summary "One line"] [--based-on brand]\n  id: lowercase letters, digits and dashes, e.g. saas or landing-v2');
  process.exit(1);
}
const target = path.join(variantsDir, id);
if (existsSync(target)) {
  console.error(`src/variants/${id} already exists.`);
  process.exit(1);
}

const name = values.name ?? id.replace(/(^|-)(\w)/g, (_, dash, c) => (dash ? ' ' : '') + c.toUpperCase());
const replacements: Record<string, string> = {
  __ID__: id,
  __NAME__: name,
  __SUMMARY__: values.summary ?? `${name} design language`,
  __BASED_ON__: values['based-on'] ?? 'brand',
};

cpSync(template, target, { recursive: true });

const walk = (dir: string): string[] =>
  readdirSync(dir).flatMap((f) => (statSync(path.join(dir, f)).isDirectory() ? walk(path.join(dir, f)) : [path.join(dir, f)]));
for (const file of walk(target)) {
  const text = readFileSync(file, 'utf8');
  const next = Object.entries(replacements).reduce((t, [k, v]) => t.replaceAll(k, v), text);
  if (next !== text) writeFileSync(file, next);
}

// Generate tokens now so styles.css can import them before the dev server notices the folder.
const core = JSON.parse(readFileSync(path.resolve(root, '../tokens/tokens.json'), 'utf8'));
const own = JSON.parse(readFileSync(path.join(target, 'tokens.json'), 'utf8'));
const { tokens, css } = buildVariant(core, own, 'Generated by playground/plugins/vite-plugin-mm-tokens.ts from tokens.json. Do not edit.');
mkdirSync(path.join(target, 'generated'), { recursive: true });
writeFileSync(path.join(target, 'generated/tokens.css'), css);
writeFileSync(path.join(target, 'generated/tokens.json'), JSON.stringify(tokens, null, 2) + '\n');

console.log(`Created src/variants/${id} (“${name}”). It appears in the playground's variant switcher.
Next: edit tokens.json (DTCG), styles.css (@theme inline utilities) and pages/.`);
