import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { Plugin, ViteDevServer } from 'vite';
import { buildVariant, type DtcgTree } from './dtcg.ts';

interface Options {
  /** Core DTCG file (tokens/tokens.json in the design-system repo). */
  coreFile: string;
  /** Folder holding one sub-folder per variant. Folders starting with `_` are templates. */
  variantsDir: string;
}

const HEADER = 'Generated by playground/plugins/vite-plugin-mm-tokens.ts from tokens.json. Do not edit.';

const readJson = (file: string): DtcgTree => (existsSync(file) ? JSON.parse(readFileSync(file, 'utf8')) : {});

function writeIfChanged(file: string, content: string) {
  if (existsSync(file) && readFileSync(file, 'utf8') === content) return;
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, content);
}

/**
 * For every variant, writes `generated/tokens.css` (custom properties layered
 * over core) and `generated/tokens.json` (resolved tokens for the docs pages).
 * Regenerates on change in dev so the canvas hot-reloads.
 */
export function mmTokens({ coreFile, variantsDir }: Options): Plugin {
  const variantIds = () =>
    readdirSync(variantsDir, { withFileTypes: true })
      .filter((d) => d.isDirectory() && !d.name.startsWith('_') && !d.name.startsWith('.'))
      .map((d) => d.name);

  const generate = (id: string) => {
    const dir = path.join(variantsDir, id);
    const { tokens, css } = buildVariant(readJson(coreFile), readJson(path.join(dir, 'tokens.json')), HEADER);
    writeIfChanged(path.join(dir, 'generated/tokens.css'), css);
    writeIfChanged(path.join(dir, 'generated/tokens.json'), JSON.stringify(tokens, null, 2) + '\n');
  };

  const generateAll = () => variantIds().forEach(generate);

  const onChange = (server: ViteDevServer) => (file: string) => {
    const isCore = path.resolve(file) === path.resolve(coreFile);
    const rel = path.relative(variantsDir, file);
    const [id, name] = rel.split(path.sep);
    const isVariant = !rel.startsWith('..') && name === 'tokens.json' && id && !id.startsWith('_');
    if (!isCore && !isVariant) return;
    try {
      if (isCore) generateAll();
      else if (existsSync(path.join(variantsDir, id))) generate(id);
      server.config.logger.info(`[mm-tokens] regenerated ${isCore ? 'all variants' : id}`, { timestamp: true });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      server.config.logger.error(`[mm-tokens] ${message}`, { timestamp: true });
      server.ws.send({ type: 'error', err: { message: `[mm-tokens] ${message}`, stack: '' } });
    }
  };

  return {
    name: 'mm-tokens',
    buildStart() {
      try {
        generateAll();
      } catch (err) {
        this.error(err instanceof Error ? err.message : String(err));
      }
    },
    configureServer(server) {
      server.watcher.add(coreFile);
      const handler = onChange(server);
      server.watcher.on('change', handler);
      server.watcher.on('add', handler);
      // A new variant folder: generate as soon as its tokens.json appears.
      server.watcher.on('addDir', (dir) => {
        const rel = path.relative(variantsDir, dir);
        if (!rel.startsWith('..') && !rel.includes(path.sep) && existsSync(path.join(dir, 'tokens.json'))) handler(path.join(dir, 'tokens.json'));
      });
    },
  };
}
